import type { CampaignIntent, LandingPageMapping, RouteAuditItem } from './types';

export const landingPageMappings: readonly LandingPageMapping[] = [
  {
    id: 'emergency_general',
    routePattern: '/emergency',
    exampleUrl: '/emergency',
    serviceSlug: 'emergency-tyre-fitting',
    requiresCity: false,
    requiresArea: false,
    finalUrlSuitability: 'yes',
    coldTrafficDefault: true,
    requiresAhmadConfirmation: false,
    isBannedFinalUrl: false,
    bestAdGroupType: 'Emergency core',
    notes: 'High-confidence emergency landing page from audited route.',
  },
  {
    id: 'emergency_near_me',
    routePattern: '/emergency-tyre-fitting-near-me',
    exampleUrl: '/emergency-tyre-fitting-near-me',
    serviceSlug: 'emergency-tyre-fitting',
    requiresCity: false,
    requiresArea: false,
    finalUrlSuitability: 'yes',
    coldTrafficDefault: true,
    requiresAhmadConfirmation: false,
    isBannedFinalUrl: false,
    bestAdGroupType: 'Emergency near me',
    notes: 'High-confidence route for urgent near-me searches.',
  },
  {
    id: 'emergency_city',
    routePattern: '/emergency-tyre-fitting/{city}',
    exampleUrl: '/emergency-tyre-fitting/glasgow',
    serviceSlug: 'emergency-tyre-fitting',
    requiresCity: true,
    requiresArea: false,
    finalUrlSuitability: 'yes',
    coldTrafficDefault: true,
    requiresAhmadConfirmation: false,
    isBannedFinalUrl: false,
    bestAdGroupType: 'Emergency city',
    notes: 'Served by the generic service-city route, so mapping must stay strict.',
  },
  {
    id: 'mobile_tyre_fitting_city',
    routePattern: '/mobile-tyre-fitting/{city}',
    exampleUrl: '/mobile-tyre-fitting/glasgow',
    serviceSlug: 'mobile-tyre-fitting',
    requiresCity: true,
    requiresArea: false,
    finalUrlSuitability: 'yes',
    coldTrafficDefault: true,
    requiresAhmadConfirmation: false,
    isBannedFinalUrl: false,
    bestAdGroupType: 'Mobile fitting city',
    notes: 'Best default for mobile tyre fitting plus city intent.',
  },
  {
    id: 'puncture_repair_city',
    routePattern: '/puncture-repair/{city}',
    exampleUrl: '/puncture-repair/glasgow',
    serviceSlug: 'puncture-repair',
    requiresCity: true,
    requiresArea: false,
    finalUrlSuitability: 'yes',
    coldTrafficDefault: true,
    requiresAhmadConfirmation: false,
    isBannedFinalUrl: false,
    bestAdGroupType: 'Puncture repair city',
    notes: 'Use for puncture repair city intent, not general tyre repair.',
  },
  {
    id: 'tyre_repair_city',
    routePattern: '/tyre-repair/{city}',
    exampleUrl: '/tyre-repair/glasgow',
    serviceSlug: 'tyre-repair',
    requiresCity: true,
    requiresArea: false,
    finalUrlSuitability: 'yes',
    coldTrafficDefault: true,
    requiresAhmadConfirmation: false,
    isBannedFinalUrl: false,
    bestAdGroupType: 'Tyre repair city',
    notes: 'Use only when keyword intent is broader than puncture repair.',
  },
  {
    id: 'tyre_fitting_city',
    routePattern: '/tyre-fitting/{city}',
    exampleUrl: '/tyre-fitting/glasgow',
    serviceSlug: 'tyre-fitting',
    requiresCity: true,
    requiresArea: false,
    finalUrlSuitability: 'yes',
    coldTrafficDefault: true,
    requiresAhmadConfirmation: false,
    isBannedFinalUrl: false,
    bestAdGroupType: 'Tyre fitting city',
    notes: 'Best default for new tyres fitted plus city intent.',
  },
  {
    id: 'tyres_catalogue',
    routePattern: '/tyres',
    exampleUrl: '/tyres',
    requiresCity: false,
    requiresArea: false,
    finalUrlSuitability: 'maybe',
    coldTrafficDefault: false,
    requiresAhmadConfirmation: false,
    isBannedFinalUrl: false,
    bestAdGroupType: 'Tyre catalogue or size',
    notes: 'Not suitable for emergency intent; only tyre shopping or size intent.',
  },
  {
    id: 'booking',
    routePattern: '/book',
    exampleUrl: '/book',
    requiresCity: false,
    requiresArea: false,
    finalUrlSuitability: 'maybe',
    coldTrafficDefault: false,
    requiresAhmadConfirmation: false,
    isBannedFinalUrl: false,
    bestAdGroupType: 'Booking or retargeting',
    notes: 'Conversion flow, not the default cold traffic page.',
  },
  {
    id: 'quote',
    routePattern: '/quote',
    exampleUrl: '/quote',
    requiresCity: false,
    requiresArea: false,
    finalUrlSuitability: 'maybe',
    coldTrafficDefault: false,
    requiresAhmadConfirmation: false,
    isBannedFinalUrl: false,
    bestAdGroupType: 'Quote or price intent',
    notes: 'Suitable for quote/price keywords, not emergency keywords.',
  },
  {
    id: 'contact',
    routePattern: '/contact',
    exampleUrl: '/contact',
    requiresCity: false,
    requiresArea: false,
    finalUrlSuitability: 'maybe',
    coldTrafficDefault: false,
    requiresAhmadConfirmation: true,
    isBannedFinalUrl: false,
    bestAdGroupType: 'Brand contact',
    notes: 'Contact page has an 8am-midnight conflict with emergency 24/7 claims.',
  },
  {
    id: 'mobile_tyre_fitting_city_price',
    routePattern: '/mobile-tyre-fitting-{city}-price',
    exampleUrl: '/mobile-tyre-fitting-glasgow-price',
    serviceSlug: 'mobile-tyre-fitting',
    requiresCity: true,
    requiresArea: false,
    finalUrlSuitability: 'needs_confirmation',
    coldTrafficDefault: false,
    requiresAhmadConfirmation: true,
    isBannedFinalUrl: false,
    bestAdGroupType: 'Price city test',
    notes: 'Suspicious route naming; must be validated before ads.',
  },
  {
    id: 'mobile_tyre_fitting_area',
    routePattern: '/mobile-tyre-fitting/{city}/{area}',
    exampleUrl: '/mobile-tyre-fitting/glasgow/city-centre',
    serviceSlug: 'mobile-tyre-fitting',
    requiresCity: true,
    requiresArea: true,
    finalUrlSuitability: 'needs_confirmation',
    coldTrafficDefault: false,
    requiresAhmadConfirmation: true,
    isBannedFinalUrl: false,
    bestAdGroupType: 'Paused area library',
    notes: 'Area routes default to paused with GBP 41/day.',
  },
  {
    id: 'emergency_area',
    routePattern: '/emergency-tyre-fitting/{city}/{area}',
    exampleUrl: '/emergency-tyre-fitting/glasgow/city-centre',
    serviceSlug: 'emergency-tyre-fitting',
    requiresCity: true,
    requiresArea: true,
    finalUrlSuitability: 'needs_confirmation',
    coldTrafficDefault: false,
    requiresAhmadConfirmation: true,
    isBannedFinalUrl: false,
    bestAdGroupType: 'Paused emergency area library',
    notes: 'Use only for confirmed fast-response areas.',
  },
  {
    id: 'puncture_repair_area',
    routePattern: '/puncture-repair/{city}/{area}',
    exampleUrl: '/puncture-repair/glasgow/city-centre',
    serviceSlug: 'puncture-repair',
    requiresCity: true,
    requiresArea: true,
    finalUrlSuitability: 'needs_confirmation',
    coldTrafficDefault: false,
    requiresAhmadConfirmation: true,
    isBannedFinalUrl: false,
    bestAdGroupType: 'Paused puncture area library',
    notes: 'Dedicated route exists, but area coverage must be confirmed.',
  },
  {
    id: 'legacy_city_hub',
    routePattern: '/services/{city}',
    exampleUrl: '/services/glasgow',
    requiresCity: true,
    requiresArea: false,
    finalUrlSuitability: 'no',
    coldTrafficDefault: false,
    requiresAhmadConfirmation: true,
    isBannedFinalUrl: true,
    bestAdGroupType: 'Do not use',
    notes: 'Legacy route with canonical to mobile tyre fitting city page.',
  },
  {
    id: 'comparison',
    routePattern: '/compare/{slug}',
    exampleUrl: '/compare/tyre-rescue-vs-kwik-fit',
    requiresCity: false,
    requiresArea: false,
    finalUrlSuitability: 'no',
    coldTrafficDefault: false,
    requiresAhmadConfirmation: false,
    isBannedFinalUrl: true,
    bestAdGroupType: 'Do not use at launch',
    notes: 'Comparison intent is not safe for GBP 41/day launch.',
  },
  {
    id: 'tracking',
    routePattern: '/tracking/{ref}',
    exampleUrl: '/tracking/TR-123',
    requiresCity: false,
    requiresArea: false,
    finalUrlSuitability: 'no',
    coldTrafficDefault: false,
    requiresAhmadConfirmation: false,
    isBannedFinalUrl: true,
    bestAdGroupType: 'Do not use',
    notes: 'Post-booking tracking route.',
  },
  {
    id: 'post_booking',
    routePattern: '/success/{ref}',
    exampleUrl: '/success/TR-123',
    requiresCity: false,
    requiresArea: false,
    finalUrlSuitability: 'no',
    coldTrafficDefault: false,
    requiresAhmadConfirmation: false,
    isBannedFinalUrl: true,
    bestAdGroupType: 'Do not use',
    notes: 'Success page after payment.',
  },
  {
    id: 'location_share',
    routePattern: '/locate/{token}',
    exampleUrl: '/locate/token',
    requiresCity: false,
    requiresArea: false,
    finalUrlSuitability: 'no',
    coldTrafficDefault: false,
    requiresAhmadConfirmation: false,
    isBannedFinalUrl: true,
    bestAdGroupType: 'Do not use',
    notes: 'Location share route for existing jobs.',
  },
  {
    id: 'pricing_faq',
    routePattern: '/pricing-faq',
    exampleUrl: '/pricing-faq',
    requiresCity: false,
    requiresArea: false,
    finalUrlSuitability: 'no',
    coldTrafficDefault: false,
    requiresAhmadConfirmation: false,
    isBannedFinalUrl: true,
    bestAdGroupType: 'Do not use at launch',
    notes: 'Support/FAQ route, not a cold final URL.',
  },
] as const;

export const routeAuditItems: readonly RouteAuditItem[] = [
  {
    routePath: '/emergency',
    pageName: 'Emergency tyre fitting Scotland',
    h1: 'Emergency tyre fitting across mainland Scotland',
    serviceIntent: 'Emergency tyre fitting',
    locationIntent: 'Mainland Scotland/general emergency',
    ctaIntent: 'Call now, book online, track fitter',
    bestGoogleAdsIntent: 'Emergency tyre fitting keywords',
    bestAdGroupType: 'Emergency core',
    suitableAsFinalUrl: 'yes',
    mixupRisk: 'Can be mixed with city-specific emergency pages.',
    namingIssue: 'None.',
    suspiciousLinkIssue: 'Track link is useful for existing customers, not ad entry intent.',
    recommendedCorrectionOrConfirmation: 'Confirm 24/7, response time, and coverage claims before ad copy uses them.',
  },
  {
    routePath: '/emergency-tyre-fitting-near-me',
    pageName: 'Emergency mobile tyre fitting near me',
    h1: 'Emergency Mobile Tyre Fitting Near You',
    serviceIntent: 'Emergency mobile tyre fitting',
    locationIntent: 'Near me and Central Scotland',
    ctaIntent: 'Call or start request',
    bestGoogleAdsIntent: 'Emergency near me keywords',
    bestAdGroupType: 'Emergency near me',
    suitableAsFinalUrl: 'yes',
    mixupRisk: 'Low. Do not use for scheduled fitting keywords.',
    namingIssue: 'None.',
    suspiciousLinkIssue: 'Service area links point to /services/{city}, which is legacy.',
    recommendedCorrectionOrConfirmation: 'Keep for near-me emergency ad group.',
  },
  {
    routePath: '/{service}/{city}',
    pageName: 'Generic service-city landing page',
    h1: '{Service} in {City}',
    serviceIntent: 'One of five audited service slugs',
    locationIntent: 'One audited city',
    ctaIntent: 'Call now, emergency callout, schedule fitting, WhatsApp',
    bestGoogleAdsIntent: 'Service plus city keywords',
    bestAdGroupType: 'Service city',
    suitableAsFinalUrl: 'yes',
    mixupRisk: 'High if emergency, puncture, and tyre repair intents are mixed.',
    namingIssue: 'Route is generic and serves many service-city URLs.',
    suspiciousLinkIssue: 'Area links generate many area URLs that should not be active by default.',
    recommendedCorrectionOrConfirmation: 'Use strict service-city mapping and validate slug intent before export.',
  },
  {
    routePath: '/{service}/{city}/{area}',
    pageName: 'Generic service-area landing page',
    h1: '{Service} in {Area}, {City}',
    serviceIntent: 'One of five audited service slugs',
    locationIntent: 'One audited city and area',
    ctaIntent: 'Call now, emergency callout, schedule fitting, WhatsApp',
    bestGoogleAdsIntent: 'Paused area library only',
    bestAdGroupType: 'Area test',
    suitableAsFinalUrl: 'needs_confirmation',
    mixupRisk: 'Very high with 2,900 possible service-area routes.',
    namingIssue: 'Area scale is too large for GBP 41/day.',
    suspiciousLinkIssue: 'Response and coverage claims vary by area and need confirmation.',
    recommendedCorrectionOrConfirmation: 'Default to paused or needs Ahmad confirmation.',
  },
  {
    routePath: '/emergency-tyre-fitting/{city}/{area}',
    pageName: 'Dedicated emergency area page',
    h1: 'Emergency tyre fitting in {area}, {city}',
    serviceIntent: 'Emergency tyre fitting',
    locationIntent: 'Specific city and area',
    ctaIntent: 'Call now and book online',
    bestGoogleAdsIntent: 'Confirmed emergency area keywords',
    bestAdGroupType: 'Emergency area test',
    suitableAsFinalUrl: 'needs_confirmation',
    mixupRisk: 'High if activated for unconfirmed areas.',
    namingIssue: 'City-only emergency URL is served by generic service-city route.',
    suspiciousLinkIssue: 'Area count is too large for launch budget.',
    recommendedCorrectionOrConfirmation: 'Activate only confirmed high-value areas later.',
  },
  {
    routePath: '/puncture-repair/{city}/{area}',
    pageName: 'Dedicated puncture repair area page',
    h1: 'Puncture repair in {area}, {city}',
    serviceIntent: 'Puncture repair',
    locationIntent: 'Specific city and area',
    ctaIntent: 'Call now and book online',
    bestGoogleAdsIntent: 'Confirmed puncture area keywords',
    bestAdGroupType: 'Puncture area test',
    suitableAsFinalUrl: 'needs_confirmation',
    mixupRisk: 'High overlap with tyre-repair keywords.',
    namingIssue: 'Breadcrumb root points to a Glasgow area URL.',
    suspiciousLinkIssue: 'Puncture and tyre repair intent can be mixed by campaigns.',
    recommendedCorrectionOrConfirmation: 'Keep puncture repair separate from tyre repair.',
  },
  {
    routePath: '/book',
    pageName: 'Booking wizard',
    h1: 'Choose how soon you need us',
    serviceIntent: 'Booking conversion',
    locationIntent: 'User-entered location',
    ctaIntent: 'Continue through booking flow',
    bestGoogleAdsIntent: 'Retargeting or booking intent',
    bestAdGroupType: 'Not default cold traffic',
    suitableAsFinalUrl: 'maybe',
    mixupRisk: 'Can bypass service explanation for cold users.',
    namingIssue: 'None.',
    suspiciousLinkIssue: 'Not a service-specific final URL.',
    recommendedCorrectionOrConfirmation: 'Use as CTA or prefilled conversion route, not default cold traffic page.',
  },
  {
    routePath: '/quote',
    pageName: 'Instant quote',
    h1: 'Get an instant quote',
    serviceIntent: 'Quote and price calculation',
    locationIntent: 'User-entered location',
    ctaIntent: 'Continue to booking',
    bestGoogleAdsIntent: 'Price or tyre-size intent',
    bestAdGroupType: 'Quote test',
    suitableAsFinalUrl: 'maybe',
    mixupRisk: 'Wrong for emergency keywords.',
    namingIssue: 'None.',
    suspiciousLinkIssue: 'Conversion flow rather than service landing page.',
    recommendedCorrectionOrConfirmation: 'Use only for quote/price campaigns after approval.',
  },
  {
    routePath: '/contact',
    pageName: 'Contact Tyre Rescue',
    h1: 'Contact our mobile tyre fitting team',
    serviceIntent: 'Support/contact',
    locationIntent: 'Glasgow, Edinburgh, Central Scotland',
    ctaIntent: 'Call, email, WhatsApp, track booking',
    bestGoogleAdsIntent: 'Brand contact only',
    bestAdGroupType: 'Brand contact',
    suitableAsFinalUrl: 'maybe',
    mixupRisk: 'High with emergency pages because hours conflict.',
    namingIssue: 'None.',
    suspiciousLinkIssue: 'States phone support is 8am to midnight while emergency pages imply 24/7.',
    recommendedCorrectionOrConfirmation: 'Ahmad must confirm hours before emergency ad copy uses 24/7.',
  },
  {
    routePath: '/tyres',
    pageName: 'Tyre catalogue',
    h1: 'Tyre Catalogue',
    serviceIntent: 'Tyre browsing',
    locationIntent: 'No fixed city',
    ctaIntent: 'Search tyres or call when no result',
    bestGoogleAdsIntent: 'Tyre size/catalogue',
    bestAdGroupType: 'Tyre catalogue',
    suitableAsFinalUrl: 'maybe',
    mixupRisk: 'Wrong for emergency or puncture repair keywords.',
    namingIssue: 'None.',
    suspiciousLinkIssue: 'Catalogue availability depends on stock data.',
    recommendedCorrectionOrConfirmation: 'Use only for tyre shopping intent.',
  },
  {
    routePath: '/tracking, /success/{ref}, /locate/{token}, /track/customer/{token}, /track/driver/{token}',
    pageName: 'Post-booking operational routes',
    h1: 'Tracking, success, or location sharing',
    serviceIntent: 'Existing customer workflow',
    locationIntent: 'Existing booking only',
    ctaIntent: 'Track or share location',
    bestGoogleAdsIntent: 'None',
    bestAdGroupType: 'Do not use',
    suitableAsFinalUrl: 'no',
    unsuitableReason: 'These routes are not acquisition landing pages.',
    mixupRisk: 'Very high waste risk if used as final URLs.',
    namingIssue: 'None.',
    suspiciousLinkIssue: 'Must never pass final URL validation.',
    recommendedCorrectionOrConfirmation: 'Block in validation.',
  },
];

export function findLandingPageMapping(intent: CampaignIntent): LandingPageMapping | undefined {
  return landingPageMappings.find((mapping) => mapping.id === intent);
}
