import { campaignRules } from './campaign-rules';
import type {
  AdCopyPlan,
  AdGroupPlan,
  CampaignPlan,
  KeywordPlan,
  LaunchPlan,
  NegativeKeywordPlan,
} from './types';

const safeEmergencyCopy: AdCopyPlan = {
  headlineIdeas: [
    'Emergency Mobile Tyre Help',
    'Call For Fast Tyre Help',
    'Book Online Or Call',
  ],
  descriptionIdeas: [
    'Mobile tyre support for urgent tyre problems. Call to confirm availability.',
    'Get local tyre fitting support at your location. Booking and phone help available.',
  ],
  riskyClaimsFlagged: [
    '24/7',
    '45 min',
    'from GBP 20',
    'GBP 49 emergency callout',
    'mainland Scotland',
    'no hidden fees',
    'fully insured',
    'Google reviews',
    'pay after service',
  ],
};

const safeMobileFittingCopy: AdCopyPlan = {
  headlineIdeas: [
    'Mobile Tyre Fitting Glasgow',
    'Local Tyre Fitting Support',
    'Book Online Or Call',
  ],
  descriptionIdeas: [
    'Mobile tyre fitting support in confirmed service areas. Book online or call.',
    'Local tyre fitting help with service details confirmed before dispatch.',
  ],
  riskyClaimsFlagged: safeEmergencyCopy.riskyClaimsFlagged,
};

const safePunctureCopy: AdCopyPlan = {
  headlineIdeas: [
    'Puncture Repair Glasgow',
    'Mobile Puncture Support',
    'Call Or Book Online',
  ],
  descriptionIdeas: [
    'Puncture support for confirmed service areas. Call to confirm repair options.',
    'Local tyre repair help when a puncture needs professional assessment.',
  ],
  riskyClaimsFlagged: safeEmergencyCopy.riskyClaimsFlagged,
};

function exactAndPhrase(text: string, intent: KeywordPlan['intent']): readonly KeywordPlan[] {
  return [
    { text, matchType: 'exact', intent },
    { text, matchType: 'phrase', intent },
  ] as const;
}

export const negativeKeywordStarterList: readonly NegativeKeywordPlan[] = [
  { text: 'jobs', reason: 'Employment intent.', editable: true },
  { text: 'career', reason: 'Employment intent.', editable: true },
  { text: 'salary', reason: 'Employment intent.', editable: true },
  { text: 'course', reason: 'Training intent.', editable: true },
  { text: 'training', reason: 'Training intent.', editable: true },
  { text: 'free', reason: 'Low commercial intent.', editable: true },
  { text: 'diy', reason: 'Self-repair intent.', editable: true },
  { text: 'how to', reason: 'Informational intent.', editable: true },
  { text: 'insurance', reason: 'Insurance intent.', editable: true },
  { text: 'tyre pressure', reason: 'Information/maintenance intent.', editable: true },
  { text: 'part worn', reason: 'Avoid low-quality or mismatched tyre intent at launch.', editable: true },
  { text: 'used tyres', reason: 'Used tyre intent is not approved for launch.', editable: true },
  { text: 'wholesale', reason: 'Trade/bulk intent.', editable: true },
  { text: 'template', reason: 'Document/template intent.', editable: true },
  { text: 'meaning', reason: 'Informational intent.', editable: true },
  { text: 'law', reason: 'Legal information intent.', editable: true },
  { text: 'mot test only', reason: 'MOT-only intent.', editable: true },
] as const;

export const recommendedCampaigns: readonly CampaignPlan[] = [
  {
    campaignName: 'Emergency Tyre Fitting Core',
    intent: 'emergency_general',
    defaultStatus: 'paused',
    notes: 'Search-only planning campaign. Search Partners and Display expansion disabled by rules.',
  },
  {
    campaignName: 'Mobile Tyre Fitting Core',
    intent: 'mobile_tyre_fitting_city',
    defaultStatus: 'paused',
    notes: 'City-service campaign for confirmed high-value locations.',
  },
  {
    campaignName: 'Puncture Repair Core',
    intent: 'puncture_repair_city',
    defaultStatus: 'paused',
    notes: 'Separate puncture intent to avoid mixing with general tyre repair.',
  },
] as const;

export const recommendedAdGroups: readonly AdGroupPlan[] = [
  {
    id: 'emergency-tyre-fitting-glasgow',
    campaignName: 'Emergency Tyre Fitting Core',
    adGroupName: 'Emergency Tyre Fitting Glasgow',
    intent: 'emergency_city',
    serviceSlug: 'emergency-tyre-fitting',
    citySlug: 'glasgow',
    finalUrl: '/emergency-tyre-fitting/glasgow',
    finalUrlSuitability: 'yes',
    launchStatus: 'active_ready',
    serviceConfirmed: true,
    cityConfirmed: true,
    finalUrlApproved: true,
    needsAhmadConfirmation: false,
    confirmationNote: 'Route exists through audited service-city route.',
    keywords: [
      ...exactAndPhrase('emergency tyre fitting glasgow', 'emergency_city'),
      ...exactAndPhrase('mobile tyre emergency glasgow', 'emergency_city'),
    ],
    adCopy: safeEmergencyCopy,
  },
  {
    id: 'emergency-tyre-fitting-near-me',
    campaignName: 'Emergency Tyre Fitting Core',
    adGroupName: 'Emergency Tyre Fitting Near Me',
    intent: 'emergency_near_me',
    serviceSlug: 'emergency-tyre-fitting',
    finalUrl: '/emergency-tyre-fitting-near-me',
    finalUrlSuitability: 'yes',
    launchStatus: 'active_ready',
    serviceConfirmed: true,
    cityConfirmed: true,
    finalUrlApproved: true,
    needsAhmadConfirmation: false,
    confirmationNote: 'Dedicated near-me route exists.',
    keywords: [
      ...exactAndPhrase('emergency tyre fitting near me', 'emergency_near_me'),
      ...exactAndPhrase('mobile tyre fitter near me emergency', 'emergency_near_me'),
    ],
    adCopy: safeEmergencyCopy,
  },
  {
    id: 'flat-tyre-glasgow',
    campaignName: 'Emergency Tyre Fitting Core',
    adGroupName: 'Flat Tyre Glasgow',
    intent: 'emergency_city',
    serviceSlug: 'emergency-tyre-fitting',
    citySlug: 'glasgow',
    finalUrl: '/emergency-tyre-fitting/glasgow',
    finalUrlSuitability: 'yes',
    launchStatus: 'active_ready',
    serviceConfirmed: true,
    cityConfirmed: true,
    finalUrlApproved: true,
    needsAhmadConfirmation: false,
    confirmationNote: 'Flat tyre intent maps to emergency city route.',
    keywords: [
      ...exactAndPhrase('flat tyre glasgow', 'emergency_city'),
      ...exactAndPhrase('flat tyre help glasgow', 'emergency_city'),
    ],
    adCopy: safeEmergencyCopy,
  },
  {
    id: 'mobile-tyre-fitting-glasgow',
    campaignName: 'Mobile Tyre Fitting Core',
    adGroupName: 'Mobile Tyre Fitting Glasgow',
    intent: 'mobile_tyre_fitting_city',
    serviceSlug: 'mobile-tyre-fitting',
    citySlug: 'glasgow',
    finalUrl: '/mobile-tyre-fitting/glasgow',
    finalUrlSuitability: 'yes',
    launchStatus: 'active_ready',
    serviceConfirmed: true,
    cityConfirmed: true,
    finalUrlApproved: true,
    needsAhmadConfirmation: false,
    confirmationNote: 'High-confidence service-city route.',
    keywords: [
      ...exactAndPhrase('mobile tyre fitting glasgow', 'mobile_tyre_fitting_city'),
      ...exactAndPhrase('mobile tyre fitter glasgow', 'mobile_tyre_fitting_city'),
    ],
    adCopy: safeMobileFittingCopy,
  },
  {
    id: 'puncture-repair-glasgow',
    campaignName: 'Puncture Repair Core',
    adGroupName: 'Puncture Repair Glasgow',
    intent: 'puncture_repair_city',
    serviceSlug: 'puncture-repair',
    citySlug: 'glasgow',
    finalUrl: '/puncture-repair/glasgow',
    finalUrlSuitability: 'yes',
    launchStatus: 'active_ready',
    serviceConfirmed: true,
    cityConfirmed: true,
    finalUrlApproved: true,
    needsAhmadConfirmation: false,
    confirmationNote: 'High-confidence service-city route. Keep separate from tyre repair.',
    keywords: [
      ...exactAndPhrase('puncture repair glasgow', 'puncture_repair_city'),
      ...exactAndPhrase('mobile puncture repair glasgow', 'puncture_repair_city'),
    ],
    adCopy: safePunctureCopy,
  },
  {
    id: 'emergency-tyre-fitting-edinburgh',
    campaignName: 'Emergency Tyre Fitting Core',
    adGroupName: 'Emergency Tyre Fitting Edinburgh',
    intent: 'emergency_city',
    serviceSlug: 'emergency-tyre-fitting',
    citySlug: 'edinburgh',
    finalUrl: '/emergency-tyre-fitting/edinburgh',
    finalUrlSuitability: 'yes',
    launchStatus: 'blocked',
    serviceConfirmed: true,
    cityConfirmed: false,
    finalUrlApproved: true,
    needsAhmadConfirmation: true,
    confirmationNote: 'Only if Ahmad confirms Edinburgh coverage and response expectations.',
    keywords: exactAndPhrase('emergency tyre fitting edinburgh', 'emergency_city'),
    adCopy: safeEmergencyCopy,
  },
  {
    id: 'mobile-tyre-fitting-edinburgh',
    campaignName: 'Mobile Tyre Fitting Core',
    adGroupName: 'Mobile Tyre Fitting Edinburgh',
    intent: 'mobile_tyre_fitting_city',
    serviceSlug: 'mobile-tyre-fitting',
    citySlug: 'edinburgh',
    finalUrl: '/mobile-tyre-fitting/edinburgh',
    finalUrlSuitability: 'yes',
    launchStatus: 'blocked',
    serviceConfirmed: true,
    cityConfirmed: false,
    finalUrlApproved: true,
    needsAhmadConfirmation: true,
    confirmationNote: 'Only if Ahmad confirms Edinburgh coverage.',
    keywords: exactAndPhrase('mobile tyre fitting edinburgh', 'mobile_tyre_fitting_city'),
    adCopy: safeMobileFittingCopy,
  },
  {
    id: 'puncture-repair-edinburgh',
    campaignName: 'Puncture Repair Core',
    adGroupName: 'Puncture Repair Edinburgh',
    intent: 'puncture_repair_city',
    serviceSlug: 'puncture-repair',
    citySlug: 'edinburgh',
    finalUrl: '/puncture-repair/edinburgh',
    finalUrlSuitability: 'yes',
    launchStatus: 'blocked',
    serviceConfirmed: true,
    cityConfirmed: false,
    finalUrlApproved: true,
    needsAhmadConfirmation: true,
    confirmationNote: 'Only if Ahmad confirms Edinburgh puncture repair coverage.',
    keywords: exactAndPhrase('puncture repair edinburgh', 'puncture_repair_city'),
    adCopy: safePunctureCopy,
  },
  {
    id: 'emergency-tyre-fitting-paisley',
    campaignName: 'Emergency Tyre Fitting Core',
    adGroupName: 'Emergency Tyre Fitting Paisley',
    intent: 'emergency_city',
    serviceSlug: 'emergency-tyre-fitting',
    citySlug: 'paisley',
    finalUrl: '/emergency-tyre-fitting/paisley',
    finalUrlSuitability: 'yes',
    launchStatus: 'blocked',
    serviceConfirmed: true,
    cityConfirmed: false,
    finalUrlApproved: true,
    needsAhmadConfirmation: true,
    confirmationNote: 'Only if Ahmad confirms Paisley coverage.',
    keywords: exactAndPhrase('emergency tyre fitting paisley', 'emergency_city'),
    adCopy: safeEmergencyCopy,
  },
  {
    id: 'emergency-tyre-fitting-east-kilbride',
    campaignName: 'Emergency Tyre Fitting Core',
    adGroupName: 'Emergency Tyre Fitting East Kilbride',
    intent: 'emergency_city',
    serviceSlug: 'emergency-tyre-fitting',
    citySlug: 'east-kilbride',
    finalUrl: '/emergency-tyre-fitting/east-kilbride',
    finalUrlSuitability: 'yes',
    launchStatus: 'blocked',
    serviceConfirmed: true,
    cityConfirmed: false,
    finalUrlApproved: true,
    needsAhmadConfirmation: true,
    confirmationNote: 'Only if Ahmad confirms East Kilbride coverage.',
    keywords: exactAndPhrase('emergency tyre fitting east kilbride', 'emergency_city'),
    adCopy: safeEmergencyCopy,
  },
  {
    id: 'emergency-tyre-fitting-hamilton',
    campaignName: 'Emergency Tyre Fitting Core',
    adGroupName: 'Emergency Tyre Fitting Hamilton',
    intent: 'emergency_city',
    serviceSlug: 'emergency-tyre-fitting',
    citySlug: 'hamilton',
    finalUrl: '/emergency-tyre-fitting/hamilton',
    finalUrlSuitability: 'yes',
    launchStatus: 'blocked',
    serviceConfirmed: true,
    cityConfirmed: false,
    finalUrlApproved: true,
    needsAhmadConfirmation: true,
    confirmationNote: 'Only if Ahmad confirms Hamilton coverage.',
    keywords: exactAndPhrase('emergency tyre fitting hamilton', 'emergency_city'),
    adCopy: safeEmergencyCopy,
  },
  {
    id: 'emergency-tyre-fitting-stirling',
    campaignName: 'Emergency Tyre Fitting Core',
    adGroupName: 'Emergency Tyre Fitting Stirling',
    intent: 'emergency_city',
    serviceSlug: 'emergency-tyre-fitting',
    citySlug: 'stirling',
    finalUrl: '/emergency-tyre-fitting/stirling',
    finalUrlSuitability: 'yes',
    launchStatus: 'blocked',
    serviceConfirmed: true,
    cityConfirmed: false,
    finalUrlApproved: true,
    needsAhmadConfirmation: true,
    confirmationNote: 'Only if Ahmad confirms Stirling coverage.',
    keywords: exactAndPhrase('emergency tyre fitting stirling', 'emergency_city'),
    adCopy: safeEmergencyCopy,
  },
] as const;

export const launchPlan: LaunchPlan = {
  name: 'GBP 41/day Google Ads safety launch plan',
  dailyBudgetGBP: campaignRules.maxBudgetPerDayGBP,
  maxActiveReadyAdGroupsDefault: campaignRules.maxActiveReadyAdGroupsDefault,
  maxActiveReadyAdGroupsStrict: campaignRules.maxActiveReadyAdGroupsStrict,
  minActiveReadyAdGroups: campaignRules.minActiveReadyAdGroups,
  matchTypesDefault: campaignRules.launchMatchTypes,
  broadMatchAllowed: campaignRules.broadMatchAllowed,
  searchPartnersAllowed: campaignRules.searchPartnersAllowed,
  displayExpansionAllowed: campaignRules.displayExpansionAllowed,
  requireManualFinalUrlApproval: campaignRules.requireManualFinalUrlApproval,
  requireManualAdGroupApproval: campaignRules.requireManualAdGroupApproval,
  campaigns: recommendedCampaigns,
  adGroups: recommendedAdGroups,
  negativeKeywords: negativeKeywordStarterList,
};

export const campaignSafetyIssues = [
  {
    id: 'contact-hours-conflict',
    severity: 'error',
    title: 'Contact page hours conflict with emergency pages',
    routePath: '/contact',
    description: '/contact says 8am-midnight while emergency pages imply 24/7 availability.',
    requiredAction: 'Ahmad must confirm the true support and dispatch hours before ad copy uses 24/7.',
  },
  {
    id: 'legacy-services-city',
    severity: 'error',
    title: 'Legacy city hub cannot be a primary final URL',
    routePath: '/services/{city}',
    description: 'This route is legacy and canonicalizes to /mobile-tyre-fitting/{city}.',
    requiredAction: 'Use the service-city route instead.',
  },
  {
    id: 'price-route-suspicious',
    severity: 'confirmation',
    title: 'Price route naming needs confirmation',
    routePath: '/mobile-tyre-fitting-{city}-price',
    description: 'The route is valid for six price city pages but naming is easy to confuse.',
    requiredAction: 'Validate route behavior before any price campaign uses it.',
  },
  {
    id: 'area-pages-budget-risk',
    severity: 'warning',
    title: 'Area pages are too many for GBP 41/day launch',
    routePath: '/{service}/{city}/{area}',
    description: 'Area-level pages create a large planning library and should not become active by default.',
    requiredAction: 'Keep area ad groups paused or blocked until specific areas are approved.',
  },
  {
    id: 'puncture-tyre-repair-overlap',
    severity: 'warning',
    title: 'Puncture repair and tyre repair overlap',
    description: 'Puncture repair keywords can be mixed with broader tyre repair intent.',
    requiredAction: 'Keep ad groups and final URLs separate by intent.',
  },
  {
    id: 'book-quote-conversion-pages',
    severity: 'warning',
    title: 'Book and quote are conversion pages',
    routePath: '/book, /quote',
    description: 'These routes are useful conversion steps but not default cold traffic pages.',
    requiredAction: 'Use only for booking, quote, or retargeting intent.',
  },
  {
    id: 'tyres-not-emergency',
    severity: 'warning',
    title: 'Tyres catalogue is not emergency intent',
    routePath: '/tyres',
    description: 'The catalogue should not be used for emergency tyre fitting keywords.',
    requiredAction: 'Use it only for tyre shopping, brand, product, or size campaigns.',
  },
  {
    id: 'tracking-success-location-blocked',
    severity: 'error',
    title: 'Tracking, success, and location-share routes are banned',
    routePath: '/tracking, /success/{ref}, /locate/{token}',
    description: 'These are post-booking operational routes and must never be final URLs.',
    requiredAction: 'Validation blocks these patterns.',
  },
] as const;
