import type { LinkableEntity, LinkingRules } from './types';

export const LINKING_RULES: LinkingRules = {
  maxLinksPerPage: 15,
  minCharsBetweenLinks: 500, // ~100 words × 5 chars
  maxSameAnchor: 2,
  priorityCategories: ['emergency', 'service', 'location'],
};

/** Weight multiplier applied to each category during relevance scoring. */
export const CATEGORY_WEIGHTS: Record<string, number> = {
  emergency: 1.0,
  service: 0.9,
  location: 0.8,
  comparison: 0.7,
  blog: 0.6,
};

/**
 * Master registry of linkable pages.
 * Priority 1-10 (10 = highest).  minDistance is chars (not words).
 * Keywords are matched case-insensitively as whole-word boundaries.
 */
export const LINKABLE_ENTITIES: LinkableEntity[] = [
  /* ────────── Emergency (priority 10) ────────── */
  {
    url: '/emergency',
    title: '24/7 Emergency Tyre Fitting',
    keywords: [
      'emergency tyre fitting',
      'emergency callout',
      'flat tyre emergency',
      'roadside assistance',
      '24/7 tyre service',
      'emergency tyre help',
      'stranded with a flat',
      'tyre blowout',
    ],
    category: 'emergency',
    priority: 10,
    minDistance: 1000,
  },

  /* ────────── Core Service × City (priority 9) ────────── */
  {
    url: '/mobile-tyre-fitting/glasgow',
    title: 'Mobile Tyre Fitting Glasgow',
    keywords: [
      'mobile tyre fitting glasgow',
      'glasgow tyre fitting',
      'mobile tyres glasgow',
      'tyre fitter glasgow',
    ],
    category: 'service',
    priority: 9,
    minDistance: 800,
  },
  {
    url: '/mobile-tyre-fitting/edinburgh',
    title: 'Mobile Tyre Fitting Edinburgh',
    keywords: [
      'mobile tyre fitting edinburgh',
      'edinburgh tyre fitting',
      'mobile tyres edinburgh',
      'tyre fitter edinburgh',
    ],
    category: 'service',
    priority: 9,
    minDistance: 800,
  },
  {
    url: '/mobile-tyre-fitting/dundee',
    title: 'Mobile Tyre Fitting Dundee',
    keywords: [
      'mobile tyre fitting dundee',
      'dundee tyre fitting',
      'tyre fitter dundee',
    ],
    category: 'service',
    priority: 8,
    minDistance: 800,
  },
  {
    url: '/mobile-tyre-fitting/stirling',
    title: 'Mobile Tyre Fitting Stirling',
    keywords: [
      'mobile tyre fitting stirling',
      'stirling tyre fitting',
      'tyre fitter stirling',
    ],
    category: 'service',
    priority: 8,
    minDistance: 800,
  },
  {
    url: '/emergency-tyre-fitting/glasgow',
    title: 'Emergency Tyre Fitting Glasgow',
    keywords: [
      'emergency tyre fitting glasgow',
      'flat tyre glasgow',
      'emergency callout glasgow',
    ],
    category: 'emergency',
    priority: 9,
    minDistance: 800,
  },
  {
    url: '/emergency-tyre-fitting/edinburgh',
    title: 'Emergency Tyre Fitting Edinburgh',
    keywords: [
      'emergency tyre fitting edinburgh',
      'flat tyre edinburgh',
      'emergency callout edinburgh',
    ],
    category: 'emergency',
    priority: 9,
    minDistance: 800,
  },
  {
    url: '/tyre-repair/glasgow',
    title: 'Tyre Repair Glasgow',
    keywords: [
      'tyre repair glasgow',
      'puncture repair glasgow',
      'tyre damage repair',
    ],
    category: 'service',
    priority: 8,
    minDistance: 800,
  },
  {
    url: '/tyre-repair/edinburgh',
    title: 'Tyre Repair Edinburgh',
    keywords: [
      'tyre repair edinburgh',
      'puncture repair edinburgh',
    ],
    category: 'service',
    priority: 8,
    minDistance: 800,
  },
  {
    url: '/puncture-repair/glasgow',
    title: 'Puncture Repair Glasgow',
    keywords: [
      'puncture repair glasgow',
      'nail in tyre glasgow',
      'slow puncture glasgow',
    ],
    category: 'service',
    priority: 8,
    minDistance: 800,
  },
  {
    url: '/tyre-fitting/glasgow',
    title: 'Tyre Fitting Glasgow',
    keywords: [
      'tyre fitting glasgow',
      'new tyres glasgow',
      'tyres fitted glasgow',
    ],
    category: 'service',
    priority: 8,
    minDistance: 800,
  },
  {
    url: '/tyre-fitting/edinburgh',
    title: 'Tyre Fitting Edinburgh',
    keywords: [
      'tyre fitting edinburgh',
      'new tyres edinburgh',
    ],
    category: 'service',
    priority: 8,
    minDistance: 800,
  },

  /* ────────── Location / Area pages (priority 7) ────────── */
  {
    url: '/mobile-tyre-fitting/glasgow/city-centre',
    title: 'Mobile Tyre Fitting Glasgow City Centre',
    keywords: ['glasgow city centre', 'city centre glasgow', 'george square', 'buchanan street'],
    category: 'location',
    priority: 7,
    minDistance: 1000,
  },
  {
    url: '/mobile-tyre-fitting/glasgow/west-end',
    title: 'Mobile Tyre Fitting West End Glasgow',
    keywords: ['west end glasgow', 'glasgow west end', 'byres road', 'kelvingrove'],
    category: 'location',
    priority: 7,
    minDistance: 1000,
  },
  {
    url: '/mobile-tyre-fitting/glasgow/southside',
    title: 'Mobile Tyre Fitting Southside Glasgow',
    keywords: ['southside glasgow', 'glasgow southside', 'queens park area'],
    category: 'location',
    priority: 7,
    minDistance: 1000,
  },
  {
    url: '/mobile-tyre-fitting/glasgow/east-end',
    title: 'Mobile Tyre Fitting East End Glasgow',
    keywords: ['east end glasgow', 'glasgow east end', 'parkhead', 'celtic park area'],
    category: 'location',
    priority: 7,
    minDistance: 1000,
  },
  {
    url: '/mobile-tyre-fitting/glasgow/partick',
    title: 'Mobile Tyre Fitting Partick',
    keywords: ['partick', 'partick cross'],
    category: 'location',
    priority: 6,
    minDistance: 1000,
  },
  {
    url: '/mobile-tyre-fitting/glasgow/shawlands',
    title: 'Mobile Tyre Fitting Shawlands',
    keywords: ['shawlands', 'pollokshaws road'],
    category: 'location',
    priority: 6,
    minDistance: 1000,
  },
  {
    url: '/mobile-tyre-fitting/glasgow/govan',
    title: 'Mobile Tyre Fitting Govan',
    keywords: ['govan', 'ibrox area'],
    category: 'location',
    priority: 6,
    minDistance: 1000,
  },
  {
    url: '/mobile-tyre-fitting/glasgow/dennistoun',
    title: 'Mobile Tyre Fitting Dennistoun',
    keywords: ['dennistoun', 'duke street area'],
    category: 'location',
    priority: 6,
    minDistance: 1000,
  },
  {
    url: '/mobile-tyre-fitting/edinburgh/leith',
    title: 'Mobile Tyre Fitting Leith',
    keywords: ['leith', 'leith walk', 'leith edinburgh'],
    category: 'location',
    priority: 7,
    minDistance: 1000,
  },
  {
    url: '/mobile-tyre-fitting/edinburgh/morningside',
    title: 'Mobile Tyre Fitting Morningside',
    keywords: ['morningside', 'morningside edinburgh'],
    category: 'location',
    priority: 6,
    minDistance: 1000,
  },
  {
    url: '/mobile-tyre-fitting/edinburgh/portobello',
    title: 'Mobile Tyre Fitting Portobello',
    keywords: ['portobello', 'portobello edinburgh'],
    category: 'location',
    priority: 6,
    minDistance: 1000,
  },

  /* ────────── Static pages (priority 7-8) ────────── */
  {
    url: '/book',
    title: 'Book a Tyre Fitting',
    keywords: ['book a fitting', 'book online', 'book tyre fitting', 'schedule fitting'],
    category: 'service',
    priority: 8,
    minDistance: 1200,
  },
  {
    url: '/tyres',
    title: 'Browse Tyres',
    keywords: ['browse tyres', 'buy tyres', 'tyre catalogue', 'tyre prices', 'cheap tyres'],
    category: 'service',
    priority: 7,
    minDistance: 1000,
  },
  {
    url: '/faq',
    title: 'Frequently Asked Questions',
    keywords: ['frequently asked questions', 'common questions', 'tyre fitting faq'],
    category: 'service',
    priority: 5,
    minDistance: 1200,
  },
  {
    url: '/contact',
    title: 'Contact Tyre Rescue',
    keywords: ['contact us', 'get in touch'],
    category: 'service',
    priority: 4,
    minDistance: 1500,
  },

  /* ────────── Blog articles (priority 6) ────────── */
  {
    url: '/blog/emergency-tyre-fitting-glasgow-complete-guide',
    title: 'Emergency Tyre Fitting Guide',
    keywords: ['emergency tyre guide', 'flat tyre guide', 'what to do flat tyre'],
    category: 'blog',
    priority: 6,
    minDistance: 1200,
  },
  {
    url: '/blog/what-to-do-flat-tyre-motorway',
    title: 'What to Do With a Flat Tyre on the Motorway',
    keywords: ['flat tyre motorway', 'motorway breakdown', 'flat tyre on motorway'],
    category: 'blog',
    priority: 6,
    minDistance: 1200,
  },
  {
    url: '/blog/mobile-tyre-fitting-vs-garage',
    title: 'Mobile Tyre Fitting vs Garage',
    keywords: ['mobile vs garage', 'garage comparison', 'mobile tyre fitting comparison'],
    category: 'blog',
    priority: 6,
    minDistance: 1200,
  },
  {
    url: '/blog/tyre-maintenance-checklist-scotland',
    title: 'Tyre Maintenance Checklist',
    keywords: ['tyre maintenance', 'tyre care', 'tyre checklist', 'check your tyres'],
    category: 'blog',
    priority: 6,
    minDistance: 1200,
  },
  {
    url: '/blog/signs-you-need-new-tyres',
    title: 'Signs You Need New Tyres',
    keywords: ['signs you need new tyres', 'worn tyres', 'tyre wear', 'replace your tyres'],
    category: 'blog',
    priority: 6,
    minDistance: 1200,
  },
  {
    url: '/blog/best-mobile-tyre-fitting-services-scotland',
    title: 'Best Mobile Tyre Fitting Services in Scotland',
    keywords: ['best mobile tyre fitting', 'tyre fitting services scotland'],
    category: 'blog',
    priority: 6,
    minDistance: 1200,
  },
  {
    url: '/blog/tyre-fitting-costs-scotland-pricing-guide',
    title: 'Tyre Fitting Costs in Scotland',
    keywords: ['tyre fitting cost', 'tyre fitting prices', 'how much does tyre fitting cost'],
    category: 'blog',
    priority: 6,
    minDistance: 1200,
  },

  /* ────────── Comparison pages (priority 7) ────────── */
  {
    url: '/compare/tyre-rescue-vs-kwik-fit',
    title: 'Tyre Rescue vs Kwik Fit',
    keywords: ['kwik fit', 'kwik fit alternative', 'kwik fit comparison'],
    category: 'comparison',
    priority: 7,
    minDistance: 1200,
  },
  {
    url: '/compare/tyre-rescue-vs-national-tyres',
    title: 'Tyre Rescue vs National Tyres',
    keywords: ['national tyres', 'national tyres comparison'],
    category: 'comparison',
    priority: 7,
    minDistance: 1200,
  },
  {
    url: '/compare/tyre-rescue-vs-ats-euromaster',
    title: 'Tyre Rescue vs ATS Euromaster',
    keywords: ['ats euromaster', 'euromaster comparison'],
    category: 'comparison',
    priority: 7,
    minDistance: 1200,
  },
  {
    url: '/compare/tyre-rescue-vs-halfords',
    title: 'Tyre Rescue vs Halfords',
    keywords: ['halfords', 'halfords tyre fitting', 'halfords comparison'],
    category: 'comparison',
    priority: 7,
    minDistance: 1200,
  },

  /* ────────── Additional service × city (priority 7) ────────── */
  {
    url: '/mobile-tyre-fitting/falkirk',
    title: 'Mobile Tyre Fitting Falkirk',
    keywords: ['mobile tyre fitting falkirk', 'falkirk tyre fitting'],
    category: 'service',
    priority: 7,
    minDistance: 800,
  },
  {
    url: '/mobile-tyre-fitting/paisley',
    title: 'Mobile Tyre Fitting Paisley',
    keywords: ['mobile tyre fitting paisley', 'paisley tyre fitting'],
    category: 'service',
    priority: 7,
    minDistance: 800,
  },
  {
    url: '/mobile-tyre-fitting/hamilton',
    title: 'Mobile Tyre Fitting Hamilton',
    keywords: ['mobile tyre fitting hamilton', 'hamilton tyre fitting'],
    category: 'service',
    priority: 7,
    minDistance: 800,
  },
  {
    url: '/mobile-tyre-fitting/east-kilbride',
    title: 'Mobile Tyre Fitting East Kilbride',
    keywords: ['mobile tyre fitting east kilbride', 'east kilbride tyre fitting'],
    category: 'service',
    priority: 7,
    minDistance: 800,
  },
  {
    url: '/mobile-tyre-fitting/motherwell',
    title: 'Mobile Tyre Fitting Motherwell',
    keywords: ['mobile tyre fitting motherwell', 'motherwell tyre fitting'],
    category: 'service',
    priority: 7,
    minDistance: 800,
  },
  {
    url: '/mobile-tyre-fitting/livingston',
    title: 'Mobile Tyre Fitting Livingston',
    keywords: ['mobile tyre fitting livingston', 'livingston tyre fitting'],
    category: 'service',
    priority: 7,
    minDistance: 800,
  },
  {
    url: '/mobile-tyre-fitting/perth',
    title: 'Mobile Tyre Fitting Perth',
    keywords: ['mobile tyre fitting perth', 'perth tyre fitting'],
    category: 'service',
    priority: 7,
    minDistance: 800,
  },
  {
    url: '/mobile-tyre-fitting/kilmarnock',
    title: 'Mobile Tyre Fitting Kilmarnock',
    keywords: ['mobile tyre fitting kilmarnock', 'kilmarnock tyre fitting'],
    category: 'service',
    priority: 7,
    minDistance: 800,
  },
  {
    url: '/mobile-tyre-fitting/ayr',
    title: 'Mobile Tyre Fitting Ayr',
    keywords: ['mobile tyre fitting ayr', 'ayr tyre fitting'],
    category: 'service',
    priority: 7,
    minDistance: 800,
  },
  {
    url: '/mobile-tyre-fitting/cumbernauld',
    title: 'Mobile Tyre Fitting Cumbernauld',
    keywords: ['mobile tyre fitting cumbernauld', 'cumbernauld tyre fitting'],
    category: 'service',
    priority: 7,
    minDistance: 800,
  },
  {
    url: '/mobile-tyre-fitting/dunfermline',
    title: 'Mobile Tyre Fitting Dunfermline',
    keywords: ['mobile tyre fitting dunfermline', 'dunfermline tyre fitting'],
    category: 'service',
    priority: 7,
    minDistance: 800,
  },
];
