export interface City {
  slug: string;
  name: string;
  county: string;
  distanceMilesFromGlasgow: number;
  lat: number;
  lng: number;
  landmarks: string[];
  nearbyAreas: string[];
  postcodePrefix: string;
}

export const cities: City[] = [
  {
    slug: 'glasgow',
    name: 'Glasgow',
    county: 'Glasgow City',
    distanceMilesFromGlasgow: 0,
    lat: 55.8642,
    lng: -4.2518,
    landmarks: ['City Centre', 'West End', 'Southside'],
    nearbyAreas: ['Govan', 'Partick', 'Shawlands', 'Pollokshields', 'Dennistoun'],
    postcodePrefix: 'G',
  },
  {
    slug: 'edinburgh',
    name: 'Edinburgh',
    county: 'City of Edinburgh',
    distanceMilesFromGlasgow: 46,
    lat: 55.9533,
    lng: -3.1883,
    landmarks: ['City Centre', 'Leith', 'Morningside'],
    nearbyAreas: ['Portobello', 'Corstorphine', 'Musselburgh', 'Dalkeith', 'Bonnyrigg'],
    postcodePrefix: 'EH',
  },
  {
    slug: 'dundee',
    name: 'Dundee',
    county: 'City of Dundee',
    distanceMilesFromGlasgow: 58,
    lat: 56.462,
    lng: -2.9707,
    landmarks: ['City Centre', 'West End', 'Broughty Ferry'],
    nearbyAreas: ['Lochee', 'Downfield', 'Monifieth', 'Carnoustie', 'Arbroath'],
    postcodePrefix: 'DD',
  },
  {
    slug: 'stirling',
    name: 'Stirling',
    county: 'Stirling',
    distanceMilesFromGlasgow: 26,
    lat: 56.1165,
    lng: -3.9369,
    landmarks: ['City Centre', 'Bridge of Allan', 'Causewayhead'],
    nearbyAreas: ['Bannockburn', 'Dunblane', 'Alloa', 'Falkirk', 'Larbert'],
    postcodePrefix: 'FK',
  },
  {
    slug: 'falkirk',
    name: 'Falkirk',
    county: 'Falkirk',
    distanceMilesFromGlasgow: 22,
    lat: 56.0019,
    lng: -3.7839,
    landmarks: ['Town Centre', 'Grangemouth', 'Larbert'],
    nearbyAreas: ['Grangemouth', "Bo'ness", 'Denny', 'Stenhousemuir', 'Polmont'],
    postcodePrefix: 'FK',
  },
  {
    slug: 'paisley',
    name: 'Paisley',
    county: 'Renfrewshire',
    distanceMilesFromGlasgow: 7,
    lat: 55.8451,
    lng: -4.4235,
    landmarks: ['Town Centre', 'Renfrew', 'Johnstone'],
    nearbyAreas: ['Renfrew', 'Johnstone', 'Elderslie', 'Linwood', 'Barrhead'],
    postcodePrefix: 'PA',
  },
  {
    slug: 'hamilton',
    name: 'Hamilton',
    county: 'South Lanarkshire',
    distanceMilesFromGlasgow: 12,
    lat: 55.7775,
    lng: -4.0393,
    landmarks: ['Town Centre', 'Motherwell', 'Larkhall'],
    nearbyAreas: ['Motherwell', 'Larkhall', 'Wishaw', 'Blantyre', 'Uddingston'],
    postcodePrefix: 'ML',
  },
  {
    slug: 'east-kilbride',
    name: 'East Kilbride',
    county: 'South Lanarkshire',
    distanceMilesFromGlasgow: 9,
    lat: 55.7644,
    lng: -4.1769,
    landmarks: ['Town Centre', 'Hairmyres', 'Westwood'],
    nearbyAreas: ['Clarkston', 'Busby', 'Strathaven', 'Chapelton', 'Stonehouse'],
    postcodePrefix: 'G75',
  },
  {
    slug: 'motherwell',
    name: 'Motherwell',
    county: 'North Lanarkshire',
    distanceMilesFromGlasgow: 13,
    lat: 55.7895,
    lng: -3.9897,
    landmarks: ['Town Centre', 'Wishaw', 'Bellshill'],
    nearbyAreas: ['Wishaw', 'Bellshill', 'Uddingston', 'Coatbridge', 'Airdrie'],
    postcodePrefix: 'ML',
  },
  {
    slug: 'livingston',
    name: 'Livingston',
    county: 'West Lothian',
    distanceMilesFromGlasgow: 28,
    lat: 55.8836,
    lng: -3.5157,
    landmarks: ['Almondvale', 'Craigshill', 'Dedridge'],
    nearbyAreas: ['Bathgate', 'Broxburn', 'Linlithgow', 'Whitburn', 'Armadale'],
    postcodePrefix: 'EH54',
  },
  {
    slug: 'kirkcaldy',
    name: 'Kirkcaldy',
    county: 'Fife',
    distanceMilesFromGlasgow: 44,
    lat: 56.1132,
    lng: -3.1615,
    landmarks: ['Town Centre', 'Dysart', 'Pathhead'],
    nearbyAreas: ['Glenrothes', 'Dunfermline', 'Burntisland', 'Methil', 'Leven'],
    postcodePrefix: 'KY',
  },
  {
    slug: 'perth',
    name: 'Perth',
    county: 'Perth and Kinross',
    distanceMilesFromGlasgow: 46,
    lat: 56.395,
    lng: -3.4313,
    landmarks: ['City Centre', 'Kinnoull', 'Scone'],
    nearbyAreas: ['Scone', 'Crieff', 'Blairgowrie', 'Auchterarder', 'Kinross'],
    postcodePrefix: 'PH',
  },
  {
    slug: 'cumbernauld',
    name: 'Cumbernauld',
    county: 'North Lanarkshire',
    distanceMilesFromGlasgow: 14,
    lat: 55.9452,
    lng: -3.9929,
    landmarks: ['Town Centre', 'Condorrat', 'Abronhill'],
    nearbyAreas: ['Kilsyth', 'Airdrie', 'Coatbridge', 'Kirkintilloch', 'Stepps'],
    postcodePrefix: 'G67',
  },
  {
    slug: 'dumfries',
    name: 'Dumfries',
    county: 'Dumfries and Galloway',
    distanceMilesFromGlasgow: 75,
    lat: 55.0704,
    lng: -3.6052,
    landmarks: ['Town Centre', 'Maxwelltown', 'Lochside'],
    nearbyAreas: ['Annan', 'Lockerbie', 'Castle Douglas', 'Sanquhar', 'Moffat'],
    postcodePrefix: 'DG',
  },
];

export function getCityBySlug(slug: string): City | undefined {
  return cities.find((c) => c.slug === slug);
}
